In [1]:
import torch
x=torch.arange(12)
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


## 张量表示由一个数值构成的数组，可以有多个维度

In [2]:
print(x.shape)
print(x.size)
X=x.reshape(3,4)#对刚才那个数组进行重排
print(X)

torch.Size([12])
<built-in method size of Tensor object at 0x00000227DB7D66C0>
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


## 通过提供包含数值的列表（其实就是矩阵）来赋确定值

In [3]:
y=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(y)
z=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(y+z)
print(y-z)
print(y*z)
print(y**z)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])
tensor([[        1,         4,        27],
        [      256,      3125,     46656],
        [   823543,  16777216, 387420489]])


## 把多个张量连接在一起 

In [4]:
X=torch.arange(12,dtype=torch.float32).reshape((3,4))
Y=torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
print(torch.cat((X,Y),dim=0))
print(torch.cat((X,Y),dim=1))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])
tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])


## 用逻辑运算符

In [5]:
print(X==Y)

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])


## 对张量中的所有元素求和

In [6]:
print(Y.sum())

tensor(30.)


## 广播机制--和numpy库类似,不同矩阵在特定情况可以相加

In [7]:
a=torch.arange(3).reshape((3,1))
b=torch.arange(3).reshape((3,1))
print(a+b)

tensor([[0],
        [2],
        [4]])


## 和numpy一样的访问元素