你可以将向量视作标量值组成的列表

In [1]:
import torch
x=torch.arange(4)
print(x)

tensor([0, 1, 2, 3])


通过张量的索引来访问任意元素

In [2]:
print(x[3])

tensor(3)


访问张量的长度

In [3]:
print(len(x))

4


通过指定m,n来创建形状为m X n的矩阵

In [4]:
A=torch.arange(20).reshape(5,4)
print(A)
print(A.T)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])
tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])


两个矩阵按元素的乘法，在数学上称为“哈达玛积”

In [5]:
B=A.clone()
print(A*B)

tensor([[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121],
        [144, 169, 196, 225],
        [256, 289, 324, 361]])


计算元素和

In [6]:
print(A.sum())
print(A.shape) # 这个不要 shape 不要加括号 ~

tensor(190)
torch.Size([5, 4])


指定求和汇总张量的轴

In [7]:
A_sum_axis0=A.sum(axis=0) # 求和每一列
print(A_sum_axis0)
print(A_sum_axis0.shape)

tensor([40, 45, 50, 55])
torch.Size([4])


In [8]:
A_sum_axis1=A.sum(axis=1) # 计算每一行的和
print(A_sum_axis1)
print(A_sum_axis1.shape)

tensor([ 6, 22, 38, 54, 70])
torch.Size([5])


In [9]:
print(A.sum(axis=[0,1]).shape)


torch.Size([])


求平均值

In [10]:
# A 是整数张量，mean() 只支持浮点/复数类型，用 .float() 转成浮点再求均值
print(A.float().mean(axis=(0,1)))

tensor(9.5000)


计算总和或均值时，保持轴数不变

In [11]:
sum_A=A.sum(axis=1,keepdims=True)
print(sum_A)

tensor([[ 6],
        [22],
        [38],
        [54],
        [70]])


可以直接广播将 A 除以 sum_A

In [12]:
print(A/sum_A)

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])


某个轴计算A元素的累加求和

In [13]:
print(A.cumsum(axis=0))

tensor([[ 0,  1,  2,  3],
        [ 4,  6,  8, 10],
        [12, 15, 18, 21],
        [24, 28, 32, 36],
        [40, 45, 50, 55]])


点积是相同位置的按元素乘积的和

In [14]:
y=torch.ones(4,dtype=torch.float32) # 全是1元素
x=x.float()
print(torch.dot(x,y)) # 是一个标量
'''
相当于
print(torch.sum(x * y))
'''

tensor(6.)


'\n相当于\nprint(torch.sum(x * y))\n'

矩阵向量积 Ax 是一个长度为 m 的向量。相当于点积 a.T * X

In [15]:
# A 是 int64(Long) 类型，x 也要转成同类型（long），torch.mv 要求两个张量 dtype 一致
x=x.long()
print(torch.mv(A,x))


tensor([ 14,  38,  62,  86, 110])


矩阵乘法！

In [19]:
B=torch.ones(4,3,dtype=torch.int64)
print(torch.mm(A,B))

tensor([[ 6,  6,  6],
        [22, 22, 22],
        [38, 38, 38],
        [54, 54, 54],
        [70, 70, 70]])


L2范数是向量元素平方和的平方根

In [20]:
u=torch.tensor([3.0,-4.0])
print(torch.norm(u))

tensor(5.)


L1范数，表示为向量元素的绝对值求和

In [21]:
print(torch.abs(u).sum())

tensor(7.)


F范数：矩阵元素平方和的平方根,相当于是L2范数的扩展

In [22]:
print(torch.norm(torch.ones(4,9)))

tensor(6.)
