假设我们想对函数y=(x.T)x关于列向量x求导

In [8]:
import torch
x=torch.arange(4.0)
print(x)

tensor([0., 1., 2., 3.])


在计算y关于x的梯度之前，我们需要一个地方来存储梯度

In [9]:
x.requires_grad_(True) # x.requires_grad_(True) 是 PyTorch 中一个非常常用的原地修改方法，它的作用是：告诉 PyTorch “我需要追踪这个张量上的所有操作，以便之后计算梯度”。

tensor([0., 1., 2., 3.], requires_grad=True)

现在我们开始计算y

In [10]:
y=2 * torch.dot(x,x)
y.backward()
print(x.grad) # 这是访问求导后导数的方法
print(x.grad==4 * x)

tensor([ 0.,  4.,  8., 12.])
tensor([True, True, True, True])


由于pytorch会累积梯度，我们需要把x之前的梯度清0

In [11]:
x.grad.zero_()

tensor([0., 0., 0., 0.])

深度学习中，我们的目的不是计算微分矩阵，而是批量每个样本单独计算的偏导数的和

In [12]:
y= x * x
y.sum().backward()
print(x.grad)

tensor([0., 2., 4., 6.])


In [13]:
x.grad.zero_()

tensor([0., 0., 0., 0.])

将一些计算移到计算图之外

In [14]:
y=x * x
u=y.detach()#这里是讲y固定成一个常数
z=u*x

z.sum().backward()
print(x.grad==u)

tensor([True, True, True, True])
