In [2]:
import torch
from torch import nn

net=nn.Sequential(nn.Linear(4,8),nn.ReLU(),nn.Linear(8,1)) #这三个层分别对应 net[0],net[1],net[2]
X=torch.randn(2,4)
print(net(X))

tensor([[-0.3238],
        [-0.3426]], grad_fn=<AddmmBackward0>)


In [8]:
print(net[2].bias)
print(net[2].weight)
print(net[2].state_dict()) # 这个层的状态
print(net[2].bias.data)
print(net[2].parameters())

Parameter containing:
tensor([-0.0380], requires_grad=True)
Parameter containing:
tensor([[-0.1045, -0.1239, -0.3482, -0.0041, -0.0650,  0.1684,  0.3483, -0.1064]],
       requires_grad=True)
OrderedDict([('weight', tensor([[-0.1045, -0.1239, -0.3482, -0.0041, -0.0650,  0.1684,  0.3483, -0.1064]])), ('bias', tensor([-0.0380]))])
tensor([-0.0380])
<generator object Module.parameters at 0x000001D8D828A180>


我们怎么对参数进行一个初始化呢？

In [9]:
def init_normal(m):
    if type(m) == nn.Linear:
        nn.init.normal_(m.weight, mean=0,std= 0.01) #均值为 0，方差为 1.
        nn.init.zeros_(m.bias)
        
net.apply(init_normal)
net[0].weight.data[0],net[0].bias.data[0]

(tensor([-0.0038,  0.0122, -0.0122, -0.0020]), tensor(0.))

In [10]:
def init_constant(m):
    if type(m) == nn.Linear:
        nn.init.constant_(m.weight, 1)
        nn.init.zeros_(m.bias)
net.apply(init_constant)
net[0].weight.data[0],net[0].bias.data[0]

(tensor([1., 1., 1., 1.]), tensor(0.))

对某些块应用不同的初始化方法

In [11]:
def xavier(m):
    if type(m) == nn.Linear:
        nn.init.xavier_uniform_(m.weight)
        
def init_42(m):
    if type(m) == nn.Linear:
        nn.init.constant_(m.weight, 42)
net[0].apply(xavier)
net[2].apply(init_42)
net[0].weight.data[0],net[2].weight.data

(tensor([ 0.5778, -0.0542, -0.2367, -0.0471]),
 tensor([[42., 42., 42., 42., 42., 42., 42., 42.]]))

自定义初始化

参数绑定