将文件保存成张量进行加载和保存

In [6]:
import torch
from torch import nn
from torch.nn import functional as F

x=torch.arange(4)
torch.save(x,'x-file')  # 把这个向量存在‘x-file’这个文件

x2=torch.load("x-file")
x2

tensor([0, 1, 2, 3])

存储一个张量列表，然后把它们读回内存

In [7]:
y=torch.zeros(4)
torch.save([x,y],'x-files')
x2,y2=torch.load("x-files")
(x2,y2)

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

写入或读取从字符串映射到张量的字典

In [8]:
mydict={'x':x,'y':y}
torch.save(mydict,'mydict')
mydict2=torch.load("mydict")
mydict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

加载和保存参数

In [9]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden=nn.Linear(20,256)
        self.output=nn.Linear(256,10)
    def forward(self,X):
        return self.output(F.relu(self.hidden(X)))
net=MLP()
X=torch.randn(2,20)
Y=net(X)

将模型的参数存储为一个叫做：mlp.params 的文件

In [10]:
torch.save(net.state_dict(),'mlp.params')

实例化了多层感知机模型的一个备份。直接读取文件中存储的参数

In [11]:
clone=MLP()
clone.load_state_dict(torch.load('mlp.params')) # 原来这里有专门封装好的函数
clone.eval()

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

一句话：eval() = 把模型切成“推理模式”，Dropout 停、BatchNorm 换统计口径；

这例子里只是养成习惯，因为没有这两类层，写不写结果都一样。

In [12]:
Y_clone=clone(X)
Y_clone==Y 

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])